// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	app2 "kart-io/kart/example/wire-example/app"
	"kart-io/kart/internal/command"
)

// Injectors from wire.go:

func wireApp() (*command.App, func(), error) {
	appApp := app2.NewConfig()
	return appApp, func() {
	}, nil
}
